framework:
  messenger:
    failure_transport: failed
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 0
      failed: 'doctrine://default?queue_name=failed'
    routing:
      App\Message\SendEmailMessage: async